name: pull_common
description: Dart package for Pull API and shared logic
version: 0.0.1

dependencies:
  riverpod: ^2.0.0-dev.8
  test: ^1.21.1
  isar: 2.5.0
  hive: ^2.2.1
  freezed: ^2.0.3+1
  http: ^0.13.4
  json_serializable: ^6.2.0

dev_dependencies:
  isar_generator: 2.5.0
  build_runner: any
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

environment:
  sdk: ">=2.17.1 <3.0.0"
